import React from 'react'
import Head from 'next/head'
import { PT_Sans } from '@next/font/google'
import styles from '../../styles/Layout.module.scss'

const ptSans = PT_Sans({ subsets: ['latin'], weight: ['400', '700'] })

export const DefaultLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>{`
        html {
          font-family: ${ptSans.style.fontFamily}, sans-serif;
        }
      `}</style>
      <header></header>
      <main className={styles.main}>
        {children}
      </main>
      <footer></footer>
    </>
  )
}
