import React from 'react'
import Head from 'next/head'
import styles from '../../styles/Layout.module.scss'

export const DefaultLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main className={styles.main}>
        {children}
      </main>
      <footer></footer>
    </>
  )
}
